### ISSUE TITLE
Doesn't work on Google Slides in Present Mode

### ISSUE THREAD

**Issue by klknaut** [tobysmith568/Confetti-Chrome-Extension#4]
This is a bummer.  There's little usefulness to this extension for me, as most of the time I need to use it, I find myself in present mode on a Google Slide and the confetti cannon doesn't work in Present Mode.  Any way to fix this problem?  It kind of takes away the spontaneity and fun of it if I have to exit out of my presentation to make the confetti pop...

**Comment by tobysmith568** [comment]
Hey @klknaut . I pushed out an update last night to fix this and Google have since accepted the update.

If you
- Go to the extensions page in your browser (probably chrome://extensions or `Ctrl + Shift +E)
- Click update (probably in the top left)

You should find that it now works on a Google Slide.

**Comment by klknaut** [comment]
I don’t see an option to update.  Would it work if I removed the extension and re-downloaded it?

**Comment by tobysmith568** [comment]
Hey @klknaut - yes uninstalling and re-installing the extension would work :)

Assuming you're using Chrome, the update button is here, and you're looking for version 1.0.1
![image](https://user-images.githubusercontent.com/22356255/99531933-640a5300-299b-11eb-85e2-d38337988ead.png)

**Comment by klknaut** [comment]
**I had to toggle on “Developer Mode” to get the update option…

**Comment by klknaut** [comment]
I’ve updated and it still doesn’t work in this mode (see screenshot): [cid:image001.png@01D6BD7F.7E564E90]

**Comment by Gitry305** [comment]
can you make it so it has customizable features, like the colors and where it fires?

**Comment by wrevell** [comment]
how do i do it
